[technote]
id = "TESTN-133"
series_id = "TESTN"
canonical_url = "https://testn-133.lsst.io"
github_url = "https://github.com/lsst-sqre-testing/testn-133"
github_default_branch = "main"
date_created = 2024-03-01T17:16:05Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "William"
name.family = "O'Mullane"
internal_id = "omullanew"
orcid = "https://orcid.org/0000-0003-4141-6195"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
address = "Avenida Juan Cisternas #1500, La Serena, Chile"
